### ISSUE TITLE
Shell scripts should set fail-fast shell options

### ISSUE THREAD

**Issue by jgreen210** [mikehardy/jetifier#13]
The shell scripts used in this repo should fail fast if commands have non-zero exit status, so that syntax errors and running out of storage space etc. make the scripts have a non-zero exit status too. Otherwise, problems in the scripts won't make the build fail directly.

That means should add this to the top of the shell scripts:

```
set -o errexit
set -o nounset
set -o pipefail
```
...and wrap any commands that do have non-zero exit status normally with an "if" (which hides the exit code from errexit).

It's nice to add bash backtraces too if use these shell options, to make it easier to debug failures. I don't have an open-source implementation of this to hand, but there will be many on the web.

Apologies for not making a PR. I've got my own hacky equivalent for this script, so can't justify spending time on testing the change.

**Comment by mikehardy** [comment]
All good ideas, thanks
