### ISSUE TITLE
When to use?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [mikehardy/jetifier#15]
Not really an issue just a clarification: when should this tool be used in favour of:
- running the official jetifier tool - https://developer.android.com/studio/command-line/jetifier
- running the "Refactor to AndroidX" option in Android Studio
- adding android.enableJetifier=true to gradle.properties

I've hit the issue in a React Native project and am confused which way to go to fix it. I'm not sure if this tool predates the 'official' ways or is still needed after in certain circumstances.

**Comment by mikehardy** [comment]
The 3 three items you mentioned are all just one thing "Migrate to AndroidX via the official documentation"

You should use this tool when you link your android dependencies via source code vs jars/aars/zips. The standard AndroidX migration refactors the source code *that exists currently*, and it dynamically re-writes packaged artifacts at build time. But it does not handle source code as it updates (like when you update or reinstall a react-native package in node_modules and it includes new non-changed support library code).

Which is to say, if you use react-native, and you use a module that has native Android code that you link in, you need this tool or a tool like it hooked in postinstall.

I have gotten this question a couple times, I'll see if I can be more clear in the docs

**Comment by JeremyBradshaw7** [comment]
Thanks Mike, it's a very useful tool and helped me get the thing compiled at last.
