### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by edenkras** [mikehardy/jetifier#16]
Followed the instructions with both yarn and npm.

With yarn:
1. `yarn add --dev jetifier`
2. `yarn run jetify`

error: The system cannot find the path specified. error Command failed with exit code 1.

With npm:
1. `npm install --save-dev jetifier`
2. `npx jetify`

error: The system cannot find the path specified.

**Comment by alexbazilev** [comment]
How did you solve this?

**Comment by mikehardy** [comment]
No one can help without information on your system. open a new issue with full information on your system. but similar to windows instructions you may need to run directly like `./node_modules/.bin/jetify`

**Comment by edenkras** [comment]
@alexbazilev I did not see the instruction to windows. download WSL (Windows Subsystem for Linux) and run the command from there.
