### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by scabezasiq** [mikehardy/jetifier#28]
Hello, when I try to execute the `npx jetify` command, I get the following messages:
`npx: installed 1 in 3.973s`
`Path must be a string. Received undefined`
`location\appName\node_modules\jetifier\bin\jetify`
`Jetifier found 1087 file(s) to forward-jetify. Using 4 workers...`

I'm not sure if that should be like that

**Comment by mikehardy** [comment]
Sounds like it wasn't installed in your project and npx tried to smooth it out with dynamic download. Was it installed locally?

**Comment by scabezasiq** [comment]
I don't sure, I followed the steps from readme file.

1. Convert your app to AndroidX via the standard AndroidX migration
2. `npm install --save-dev jetifier`
3. `npx jetify`
4. `npx react-native run-android` (your app should correctly compile and work)
5. Call `npx jetify` run in the postinstall target of your package.json (Any time your dependencies update you have to jetify again)

Is there any step that I missed?

**Comment by mikehardy** [comment]
no that is supposed to be it :thinking: - why would npx say it installed something if it was already installed? Is there something special about the directory you need to be in when you invoke `npx jetify`? are the results different if you do `./node_modules/.bin/jetify` ?

**Comment by mikehardy** [comment]
no feedback
