### ISSUE TITLE
Improve performance of jetify source processing

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/jetifier#3]
Currently running jetify can be very slow

There are likely a bunch of methods to speed it up via tools used alone (maybe getting an xargs pipeline or find/exec to work, or switching from shell to multi-threaded javascript or something)

There is an opportunity to only convert things that need converting by maintaining a blacklist of regular expressions not to convert maybe, or alternatively a whitelist of only the regular expressions to convert

Any PRs are welcome

**Comment by cawfree** [comment]
Thanks for this great tool @mikehardy!

Just to add to this, I wonder if it would be possible to avoid processing any file contents which like under `app/build/` directories, since these intermediate results could just be re-populated after making a new build. Might be a quick gain.

**Comment by mikehardy** [comment]
I am sure this is possible - probably a trivial change to the script if you have time to try it? I'm pretty busy today on a bunch of repositories today with big userbases just doing user education and don't have time for enhancements at the moment - the changes are easy but to test it and make sure takes a little more time (not much but...)

**Comment by cawfree** [comment]
Hey, absolutely I'll gladly take a look. Unfortunately bash isn't exactly my speciality, but I'll try to do a little reading around it and see if I can come up with something.

Thanks again!

**Comment by jgreen210** [comment]
It'll generally only be a relatively minor improvement, but could use find's -prune option for .git directories. This would avoid scanning all the files in these directories.

**Comment by jgreen210** [comment]
sed's -i option takes a `''` value, which would prevent creation of backup files, wouldn't need to delete them. Could then use `find -exec sed -i '' -f "${MAPPING_SED}" '{}' '+'`. That might be a little quicker, and would work better for paths with spaces etc.

**Comment by jgreen210** [comment]
I got decent speed here by only applying the large list of replacements to a line if it includes the substring "android.support".  sed is probably quicker than most scripting languages, but not if it has to loop through many patterns for every line.

**Comment by mikehardy** [comment]
@jgreen210 I think it already discards the .git directories but maybe prune is a more efficient way. The -i pointer sounds interesting but I had a lot of compatibility issues with BSD sed on macOS and went back and forth on it. Going to stay with how it is now. Maybe you could just post the bit that is the improvement? take + give :-)

**Comment by mikehardy** [comment]
Resolved with #5 but if someone posted the sed-kung-fu (or a pointer to it) to skip replacement checking if android.support wasn't on a line, that would be awesome
