### ISSUE TITLE
Help to revert breaking changes

### ISSUE THREAD

**Issue by jdnichollsc** [mikehardy/jetifier#31]
Hi @mikehardy, thanks for this tool!

I was wondering if you can help me to identify what changes I need to revert to use this tool instead of having breaking changes?
I'm the maintainer of this library: https://github.com/proyecto26/react-native-inappbrowser/commit/8a083f24847ac5f49923c6217106628434634b4d#diff-7ae5a9093507568eabbf35c3b0665732

Thanks in advance 👍

**Comment by mikehardy** [comment]
Hi there! Sorry, I can't look at individual libraries to help them upgrade - I can't scale out that far ;-). That said, I would not avoid AndroidX changes in your library. I would implement AndroidX as a breaking change with a major version bump and move on. I would try to be sensitive to people stuck on RN0.59 by trying to do so in a way that "jetify -r" would work for the new AndroidX version of your library but that shouldn't be too hard. You can try putting your library into a local clone of the rn-androidx-demo https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh while it is set to RN0.59 to verify it works with reverse-jetify, and if it does, you're not just set for the future, but have helped your temporarily-stuck-on-non-AndroidX users. Can't ask for more from a library maintainer than that

**Comment by jdnichollsc** [comment]
Thanks Mike for your comments! 💯
