### ISSUE TITLE
android.support.v7.widget.GridLayoutManager not converted correctly

### ISSUE THREAD

**Issue by mysport12** [mikehardy/jetifier#32]
For some reason GridLayoutManager is not being converted correctly with jetifier. After running 'npx jetify' the import statement is converted to:

'import androidx.gridlayout.widget.GridLayoutManager;' instead of
'import androidx.recyclerview.widget.GridLayoutManager;'

<img width="890" alt="image" src="https://user-images.githubusercontent.com/10301026/61134223-26cfb000-a48d-11e9-9a1c-9300dfc1e7c7.png">

Package where error surfaced: react-native-photo-editor

**Comment by mikehardy** [comment]
I bet this is a simple regex issue - matching substrings instead of only full matches. The regex we use in Javascript should be similar to python or Java and I'm sure there will be an example of a correct one in some other implementation. If you want to try to hunt for one and make a pr that would help, or at least add photo-editor to the androidx demo CI project as a PR to surface the error? Good find

**Comment by mysport12** [comment]
One thought I had was simply sorting the csv file in Descending order instead of Ascending order. That was the longer library names will get processed before the shorter names

<img width="895" alt="image" src="https://user-images.githubusercontent.com/10301026/61157833-3ec32600-a4c5-11e9-82b9-644350dc0f13.png">

Not sure if that is a possibility or if it is too fragile of an approach. Testing locally to see if it resolves the problem

**Comment by mysport12** [comment]
Did a fresh node modules install with my forked version that uses the Descending sort method and got a successful build. I'll submit a PR for evaluation. And thank you for this package. Total life saver with this AndroidX migration!!!

**Comment by mikehardy** [comment]
I would love to stay with the official csv as the one we work from so people can checksum it etc and the chain of trust goes up to google, but perhaps the array of substitutions read in from the csv could be sorted longest to shortest, then applied? I see you made the PR and it's a mod to the CSV - just asking quickly if you think you could modify it to do an array sort by length post-processing? If not, I'll merge as is

The general idea of longest to shortest is clever - I can't think why that wouldn't work in the general case, and I'm glad it's working for you at minimum.

**Comment by mysport12** [comment]
I like the proposed approach better as well using array length. Keeping the original csv definitely provides more peace of mind which is a good thing amongst all the change. I’ll give this a shot with my code base to make sure it’s still working but don’t see a reason why it shouldn’t.

**Comment by mikehardy** [comment]
I just finished working through what photo-editor needs to work correctly in the CI test suite I use here and I lodged a PR upstream, I think you'll need to use my jetifier-support branch on my fork until the PR is accepted. I won't have time to follow up on that PR so if you could run with it, that would be awesome - I just did what was needed to make it pass `./gradlew assembleRelease` - I did not test it to see if it actually worked https://github.com/prscX/react-native-photo-editor/pull/72

**Comment by mikehardy** [comment]
Want to say again this was a great find - the first core translation bug we've had logged really, glad to have it fixed - thanks!

**Comment by mikehardy** [comment]
released just now in 1.6.3

**Comment by mysport12** [comment]
Awesome! Thanks again for all the help on this one and another shout out for an amazing tool to make all of our lives much easier with the AndroidX migration.
