### ISSUE TITLE
Npx Jetify doesnt affect release builds

### ISSUE THREAD

**Issue by rafalkaczynsky** [mikehardy/jetifier#35]
Npx Jetify doesnt affect release builds, only dev ones. Any ideas?

**Comment by songxiaoliang** [comment]
@rafalkaczynsky Hi, How can I solve this?

**Comment by mikehardy** [comment]
https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh#L161

There is nothing special about a debug vs a release build from jetifier's perspective.

**Comment by songxiaoliang** [comment]
@mikehardy I combined fastlane to upload apk, but there was an error during the packaging process.

`
    gradle(
      task: "clean assembleRelease",
      properties: {
        "versionName" => options[:versionName],
      }
    )
`

**Comment by mikehardy** [comment]
and the error was...

**Comment by songxiaoliang** [comment]
@mikehardy I solved this problem by executing npx jetify. thanks
