### ISSUE TITLE
React Native v0.60.0 & AndroidX Migration

### ISSUE THREAD

**Issue by ganico** [mikehardy/jetifier#37]
any idea why i'm experiencing this.. 

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :app
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :app > project :blinkid-react-native
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :app > com.facebook.react:react-native:0.60.3
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :app > project :react-native-fbsdk
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :app > com.facebook.android:facebook-android-sdk:4.22.1

-----------------------------------------------------------------------------------------------
I also attached the one i'm encountering when running using android studio :( NOT sure if the issues are both related.. i use jetifier when I migrated

<img width="970" alt="Screenshot 2019-07-16 at 15 05 25" src="https://user-images.githubusercontent.com/7714293/61273465-311ae280-a7dc-11e9-852c-4354e3134577.png">

**Comment by WebMobi59** [comment]
@ganico could you possibly let me know how did you resolve this issue?
I am getting same issue now.

**Comment by ganico** [comment]
> @ganico could you possibly let me know how did you resolve this issue?
> I am getting same issue now.

i'm actually still fixing the issue but on this part I think you just need to import the following dependency that's mentioned there then if still not working try to convert your current project to AndroidX again (not sure but it might help since whenever you delete the node_modules, after npm install it'll create another library files which is not AndroidX anymore)

Just give a shot because my issue now is regarding hermes something BWOHOHO!!
