### ISSUE TITLE
don't change anything in @aws-amplify/pushnotification

### ISSUE THREAD

**Issue by matamicen** [mikehardy/jetifier#41]
@mikehardy first of all, thanks for this library it saves a lot of time :). 
Do you know that NPX jetify doesn't change this line in the amplify pushnotification gradle:
```

//  compile "com.android.support:appcompat-v7:23.0.1"
    compile "androidx.appcompat:appcompat:1.0.0"
```
We had to change it manually. 
I hope this help someone.

Thanks again!
Matt.

**Comment by mikehardy** [comment]
Item 2 here - it's a library issue, nothing we can do: https://github.com/mikehardy/jetifier#module-maintainers
