### ISSUE TITLE
react-native-firebase doubt

### ISSUE THREAD

**Issue by matamicen** [mikehardy/jetifier#42]
Hi @mikehardy @matt-oakes 

I have a doubt, after executing npx jetify is solves all the problems of react-native-firebase and everything is working ok but in the gradle library i saw this line which I suspect isnt compatible with androidX ? 

```
...
// For React Native Firebase Notifications
  api "com.android.support:support-v4:$supportVersion"
...
```

it suppose that I have to change this manually? or I am missing something ?

Again: besides this line everything seems to work okay.

Thanks for your support to the community.

Matt.

**Comment by mikehardy** [comment]
Probably item 2 here https://github.com/mikehardy/jetifier#module-maintainers

But in general I believe the Android Studio / Gradle java-level jetifier library will transform the library references correctly
