### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by BenWildeman** [mikehardy/jetifier#43]
I ran into an issue with trying to use npx jetify as a postinstall script within docker. The problem here is that for some reason, the node_modules end up being owned by a different user, or nobody, or whatever, and that means that npm will throw an ambigious error of `cannot run in wd <package> npx jetify`.

The simple fix is to add `RUN npm set unsafe-perm true` to the dockerfile before an npm (or friends) install

**Comment by mikehardy** [comment]
Okay - if you want to post a PR to the troubleshooting section I can merge it - but this doesn't seem like it's jetifier's fault per se - so I'll close
