### ISSUE TITLE
How to handle build.gradle files with outdated references?

### ISSUE THREAD

**Issue by augustl** [mikehardy/jetifier#44]
It seems that this library by design reads java files, xml files and kotlin files - but not build.gradle-files. This causes my project to not convert properly, since I have the following modules that aren't updated:

    // react-native-cross-geolication:
    implementation "com.android.support:appcompat-v7:${_supportLibVersion}"
    
    // react-native-maps:
    implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '28.0.0')}"
    
    // react-native-camera:
    implementation "com.android.support:exifinterface:${safeExtGet('supportLibVersion', '27.1.0')}"
    implementation "com.android.support:support-annotations:${safeExtGet('supportLibVersion', '27.1.0')}"
    implementation "com.android.support:support-v4:${safeExtGet('supportLibVersion', '27.1.0')}"

The refactoring tool in Android Studio catches these, and changes the files respectively to:

    // react-native-cross-geolication:
    implementation "androidx.appcompat:appcompat:${_supportLibVersion}"
    
    // react-native-maps:
    
    implementation "androidx.appcompat:appcompat:1.0.0-beta01"
    
    // react-native-camera:
    
    implementation "androidx.exifinterface:exifinterface:1.0.0-beta01"
    implementation "androidx.annotation:annotation:1.0.0-beta01"
    implementation "androidx.legacy:legacy-support-v4:1.0.0-beta01"

I can of course manually  run the refactoring tool in Android Studio when required, but maybe there's a way to make this tool handle these cases as well?

**Comment by mikehardy** [comment]
It's also the case most maintainer work and troubleshooting here is focused on the deoendenc management in gradle files. I wasn't aware android studio did those automatically but if there was a reliable automated way to do it that would be fantastic

Does the mapping file already contain the correct mappings? I'm traveling now so can't check

**Comment by OleksandrKucherenko** [comment]
declare file `overrides.gradle` in solution:

```groovy
subprojects {
    configurations.all {
        // exclude OLD versions of OKHTTP library
        exclude group: 'com.squareup.okhttp', module: 'okhttp'

        // exclude rxJava v1.xxx
        exclude group: 'io.reactivex', module: 'rxjava'
        exclude group: 'io.reactivex', module: 'rxandroid'

        // NOTE (olku): we have to use for-each approach, otherwise hidden/runtime configurations
        // will not be caught and properly forced/updated to needed to us libs versions.
        resolutionStrategy {
            failOnVersionConflict()
            preferProjectModules()

            eachDependency { details ->
                /* Override by group name */
                switch (details.requested.group) {
                    case 'com.android.support': details.useVersion '27.1.1'; break

                    case 'com.facebook.fresco':
                        details.useVersion '1.13.+'
                        break
                }

                /* Override by group and library names */
                def name = "${details.requested.group}:${details.requested.name}"
                switch (name) {

                    /* lib exists only in v28.0.0 */
                    case 'com.android.support:localbroadcastmanager':
                        /* https://mvnrepository.com/artifact/com.android.support/localbroadcastmanager */
                        details.useTarget group: details.requested.group, name: 'support-v4', version: '27.1.1'
                        details.because 'LocalBroadcastManager is a part of support library before 28.0.0'
                        break

                    /* Override library to 'migration' package that depends on support library instead of androidx */
                    case 'com.klarna.checkout:sdk':
                        /* https://artifactory.klarna.net/artifactory/l-maven-mobile-sdk-releases/com/klarna/checkout/sdk/ */
                        details.useVersion '1.6.10-support'
                        break

                    case 'com.android.support:multidex-instrumentation':
                    case 'com.android.support:multidex':
                        /* multidex has own version sequence in support group */
                        details.useVersion '1.0.3'
                        break
//*
                    case 'androidx.appcompat:appcompat': details.useVersion '1.0.2'; break
                    case 'androidx.core:core': details.useVersion '1.0.1'; break
                    case 'androidx.vectordrawable:vectordrawable': details.useVersion '1.0.1'; break
//*/
                }
            }
        }
    }
}


subprojects { prj ->
    prj.buildscript {
        /* inject our repository into buildscript of each sub-project */
        repositories {
            /* Needed for Google Pay */
            google()
            jcenter()
            mavenCentral()
            maven { url 'https://maven.fabric.io/public' }
            flatDir { dirs "${rootProject.projectDir}/app/libs" }
        }
        /* force build plugin version of our root project */
        configurations.classpath {
            resolutionStrategy {
                force 'com.android.tools.build:gradle:3.5.0'
            }
        }
    }
}
```

and include `overrides.gradle` to `build.gradle`:

```groovy
/* Load dependencies override script. */
apply from: file('overrides.gradle')
```

**Comment by mikehardy** [comment]
We should all be using `--no-jetifier` in our builds (I am, successfully) at this point, and this repo should be sunset, I don't expect to make further changes in it
