### ISSUE TITLE
Handle AndroidManifest.xml <provider> android.support.v4.content.FileProvider => androidx.core.content.FileProvide

### ISSUE THREAD

**Issue by esutton** [mikehardy/jetifier#46]
Thanks for a great tool!

Perhaps this could be supported?
````
<provider
        android:name="android.support.v4.content.FileProvider"
      .....
</provider>
````
To this one
````
<provider
    android:name="androidx.core.content.FileProvider"
    ......
</provider>
````

**Comment by mikehardy** [comment]
I believe it is?
https://github.com/mikehardy/jetifier/blob/master/mapping/androidx-class-mapping.csv#L1404

Happy to reopen this if there’s a deeper cause that jetifier is messing up somehow (those are usually very instructive…) but I would suspect some sort of local toolchain issue at the moment as this should work and is a fairly common case - in my own project even
