### ISSUE TITLE
androidx.core.util.pair isn't reversed

### ISSUE THREAD

**Issue by Dror-Bar** [mikehardy/jetifier#48]
Hey all, first of all let me say this is a really useful library, thanks a lot!

I was using this library for the reverse functionality with the -r flag. It worked as expected, however it missed one import which is androidx.core.util.pair, and I had to manually change it to android.support.v4.util.Pair. This should probably be implemented in master.

Thanks.

**Comment by mikehardy** [comment]
Strange, it's in the mapping https://github.com/mikehardy/jetifier/blob/master/mapping/androidx-class-mapping.csv#L1553

perhaps it is the capital letter vs not capital letter?

**Comment by mikehardy** [comment]
please give an example of a react-native module that exhibits the behavior so we can check

**Comment by Dror-Bar** [comment]
It happened to me with react-native-view-shot.

However, my colleague just tried it and it worked for him.
I think it may have to do with me changing the code manually (I may have added a space).
So it's probably working on a clean module.
Closing.

**Comment by mikehardy** [comment]
whew! :-), thank you for double-checking - happy coding!
