### ISSUE TITLE
npx jetifier not giving any reslut

### ISSUE THREAD

**Issue by karthikmandava7** [mikehardy/jetifier#49]
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 897 file(s) to forward-jetify. Using 4 workers...

**Comment by mikehardy** [comment]
there is no output expected after that. it would throw errors if there were any, but if things proceed normally and your `react-native start` command proceeds, you're fine.

If it does not proceed, then you've run into this: #40
