### ISSUE TITLE
Is this included by default with a certain React Native version?

### ISSUE THREAD

**Issue by taylorkline** [mikehardy/jetifier#52]
I have recently upgraded from RN 0.57.2 to RN 0.61.2.

When I run `react-native run-android`, I see:

> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.

In the log messages.

Is `run-android` doing exactly what downloading jetifier and running it manually would do? Or is it still necessary or advantageous to download and run jetifier manually?

**Comment by mikehardy** [comment]
For react-native 0.60+ it is integrated in the @react-native-community/cli version that react-native depends on, and it runs for you by default, yes. 

As a community we all figured that was a much better developer experience than instructing everyone to do it manually, and even if it runs twice (for people that manually integrated already) it doesn't hurt and doesn't take too long.

**Comment by taylorkline** [comment]
Thanks! Would you support adding this fact to the README to avoid confusion?
________________________________

**Comment by mikehardy** [comment]
sure! propose anything sensible for it as a PR and I'll merge it immediately
