### ISSUE TITLE
readDir Infinite loop

### ISSUE THREAD

**Issue by gaodeng** [mikehardy/jetifier#55]
When there is a symlink to the parent folder in the node_modules folder, it  will loop indefinitely.

https://github.com/mikehardy/jetifier/blob/4e1f1198337bb99eef5a7dd3cac3c5316ea2e1c6/src/utils.js#L20

**Comment by mikehardy** [comment]
Interesting, I was not aware react-native tools (metro etc) handled symlinks?

Try a patch where you do readDir but with options set to withFileTypes
https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback

Then only recur if it isSymblicLink is false
https://nodejs.org/api/fs.html#fs_class_fs_dirent
https://nodejs.org/api/fs.html#fs_dirent_issymboliclink

You can hack on it right in node_modules to test, work of a couple minutes. If it works use patch-package to generate a patch so you are fixed locally and submit a PR, I'll merge it in

**Comment by gaodeng** [comment]
@mikehardy  metro can not handled symlinks . I am manually  add symlink package to watchFolders in metro.config.js .
here the PR https://github.com/mikehardy/jetifier/pull/56

**Comment by gaodeng** [comment]
resolved in v1.6.5
