### ISSUE TITLE
npx jetify - npm registry fails

### ISSUE THREAD

**Issue by rborn** [mikehardy/jetifier#59]
Hi, 

I just started to get this (I call `npx jetify`), any ideas?

`Not Found - GET https://registry.npmjs.org/jetify - Not found`

Thank you 😍

**Comment by mikehardy** [comment]
Hey @rborn jetify is actually an alias, the package is officially 'jetifier', `npx jetify` will work *once it is installed in a project* because we make a `node_modules/.bin/jetify` link but will not work otherwise

Can you confirm that information makes sense in the context of the failure you see?

**Comment by rborn** [comment]
mmm, something happened with my project then, the link is not there...

**Comment by mikehardy** [comment]
Very strange. `npx jetifier` is the canonical name for it to encode in places, we just put in the syntactic sugar jetify because so many people wanted to refer to it in verb form. I'll see what you find :-)

**Comment by rborn** [comment]
Ok, so `npm install --save-dev jetifier` added the symlink, but `npm install` doesn't 🥺

**Comment by rborn** [comment]
So old magic `rm package-lock.json &&  rm node_modules` did the trick :man_facepalming: 
Sorry for the mess 😞

**Comment by mikehardy** [comment]
It's all just a house of cards, waiting for the wind to blow 😅  - Cheers
