### ISSUE TITLE
Recommend running jetify on postinstall

### ISSUE THREAD

**Issue by mgtitimoli** [mikehardy/jetifier#6]
Hi there,

Before moving forward I want to thank you for having created this package!

I currently don't have the time to fork and send you a PR, but I'm opening this one so next time you push something you consider adding to README a recommendation of running jetify in the postinstall script, so this way you won't need to manually run jetify each time you add/remove a package.

**Comment by mikehardy** [comment]
That's a really good idea - and I want to do it. For now the performance was admittedly pretty awful and I felt bad recommending it, but with the good work @cawfree is doing in #5 I think there will be something performant very quickly, at which point - yes! This will be the best way to make sure things stick. If the ordering is right, people can even continue to use patch-package, which is a nice outcome

**Comment by mgtitimoli** [comment]
Nice, so maybe @cawfree can add this little comment to the README in #5 then?

**Comment by mikehardy** [comment]
that would be :+1: by me if so, if not I'll get it

**Comment by dinilat** [comment]
Not able to run npx jetify in cmd on windows.  Getting error "The system cannot find the path specified.". is there anything I am missing. Please help me out.

**Comment by mikehardy** [comment]
Hi there @dinilat ! I haven't implemented or tested it on windows at all. It was developed on linux and macOS, but I would assume for find, sort and sed to work you will need something like cygwin or linux subsystem for windows, or a .bat implementation of it? Can you open a new issue for Windows support, with what you ran, and the exact output?
