### ISSUE TITLE
No mapping for: androidx/viewbinding/ViewBinding

### ISSUE THREAD

**Issue by dosomet** [mikehardy/jetifier#68]
source aar used viewbinding when 

./jetifier-standalone -r -i xx.aar -o support.aar

WARNING: [CoreRemapperImpl] No mapping for: androidx/viewbinding/ViewBinding

**Comment by mikehardy** [comment]
Hi there! This project is effectively deprecated, AndroidX transition should be complete now, I won't spend any more time working on it personally but if you propose a PR I could take a look.
