### ISSUE TITLE
npm install jetifier fail

### ISSUE THREAD

**Issue by HiconKong** [mikehardy/jetifier#7]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for websocket-driver@0.7.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'faye-websocket'
npm ERR! notarget

**Comment by mikehardy** [comment]
Hi there! This indeed looks like total failure, but...I don't depend on faye-websocket anywhere, or websocket-driver, sorry. This is unrelated to this project. You can inspect https://github.com/mikehardy/rn-androidx-demo/ to see it working
