### ISSUE TITLE
Can't run npx jetify on React Native 0.70.5

### ISSUE THREAD

**Issue by timothyerwin** [mikehardy/jetifier#72]
I'm trying to fix a separate problem that says to use this tool but when I follow the installation instructions it says

```sh
$ npm install --save-dev jetifier
$ npx jetify
Your Princess is in Another Castle!

  Please consider installing 'jetifier' package before running 'jetify' command!

Exiting...
```

The jetifier package is installed and I also tried to install it globally with the same result.

**Comment by mikehardy** [comment]
Hi there!

A couple things: this tool is deprecated, no current software should be using it, and upstream bugs should be filed / patch-package on the offending modules should be filed

Second is that if you have installed jetifier, then npx jetify should work, if it is not, I'm not sure what is going on but it contradicts my experience. I suppose you could also directly execute `./node_modules/.bin/jetify` and that would also work

But no one should use jetifier anymore - Compat --> AndroidX migration should be all complete by now in all modules and stragglers need fixing ASAP as jetifier was removed from react-native CLI
