### ISSUE TITLE
Not converting the import statements.

### ISSUE THREAD

**Issue by Saad-Bashar** [mikehardy/jetifier#9]
I am using few libraries like react-native-fbsdk, react-native-image-picker and so on. First I moved to androidx by changing gradle properties. So I use this library, it does some conversion.  But all these third party library are importing android.support.library in their source code. So it is getting build failed. One of the examples are given here. It is happening in react-native-fbsdk. 

<img width="480" alt="Screen Shot 2019-06-19 at 4 15 55 PM" src="https://user-images.githubusercontent.com/13269141/59748404-a1057e00-92ad-11e9-9d72-c4e774e4bb10.png">

**Comment by mikehardy** [comment]
I tried but was unable to reproduce? Fork the demonstrator and make it fail, then we can fix? https://github.com/mikehardy/rn-androidx-demo/commit/a5ee3f894470b310144e8c94bd1ec94862b08b6b

**Comment by Saad-Bashar** [comment]
I did android studio migration finally. It worked.

**Comment by Saad-Bashar** [comment]
I have a question. What is the difference between android studio and your package?

**Comment by mikehardy** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/129 has the details

Basically Android studio can handle your source, and the built-in jetifier can handle jars and aars and zips, but there is no built-in tool that can transform dependencies that are linked in via source.

And react-native primarily links in via source, so we have to transform the source code itself, and that's what the `npx jetify` command does...

**Comment by mikehardy** [comment]
Happy to hear it's working for you though :-)
